version: "3.9"
services:
  devcontainer:
    build:
      dockerfile: Dockerfile
    volumes:
      - hadoop_config:${HADOOPCONFDIR}
    networks:
      - BIG-dataplatform-network

volumes:
  hadoop_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4,nolock,hard
      device: ":${NFSPATH}/dataplatform_config/hadoop_conf/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
